# Generated by Django 4.1.1 on 2022-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stud_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_name", models.CharField(max_length=30)),
                ("s_class", models.CharField(max_length=30)),
                ("s_address", models.CharField(max_length=30)),
                ("s_school", models.CharField(max_length=30)),
                ("s_email", models.EmailField(max_length=30)),
            ],
        ),
    ]
